import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import MarkdownIt from 'markdown-it';
import texmath from 'markdown-it-texmath';
import katex from 'katex';

const root=path.resolve(fileURLToPath(new URL('..',import.meta.url))),out=path.resolve(root,'dist');
process.chdir(root);
const site=JSON.parse(fs.readFileSync('site.json','utf8'));
const escape=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const markdown=new MarkdownIt({html:false,linkify:true}).use(texmath,{engine:katex,delimiters:['dollars','brackets'],katexOptions:{throwOnError:true,trust:false,strict:'warn',maxExpand:1000}});
function write(file,content){const target=path.join(out,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content);}
function safeUrl(value){const url=new URL(value);if(!['https:','http:'].includes(url.protocol))throw new Error('Unsupported link protocol');return escape(url.href);}
function parsePost(file){
  const raw=fs.readFileSync(path.join('content/posts',file),'utf8').replace(/^\uFEFF/,'').replaceAll('\r\n','\n');
  const match=raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!match)throw new Error('Missing article metadata: '+file);
  const meta={};for(const line of match[1].split('\n')){if(!line.trim())continue;const entry=line.match(/^([a-z_]+):\s*(.*)$/);if(!entry)throw new Error('Invalid article metadata: '+file);const value=entry[2].trim();meta[entry[1]]=value.startsWith('"')||value==='true'||value==='false'?JSON.parse(value):value;}
  const slug=file.slice(0,-3);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw new Error('Invalid article filename: '+file);
  if(!meta.title||!/^\d{4}-\d{2}-\d{2}$/.test(meta.date??'')||Number.isNaN(Date.parse(meta.date)))throw new Error('Article needs title and date: '+file);
  if(!['随笔','研究','开发'].includes(meta.category))throw new Error('Invalid category: '+file);
  return {...meta,slug,body:match[2],html:markdown.render(match[2])};
}
fs.mkdirSync('content/posts',{recursive:true});
const allPosts=fs.readdirSync('content/posts').filter(file=>file.endsWith('.md')).map(parsePost);
const posts=allPosts.filter(post=>post.draft!==true).sort((a,b)=>b.date.localeCompare(a.date)||a.slug.localeCompare(b.slug));
const icon=(type)=>{const paths={moon:'<path d="M20.9 13A9 9 0 0 1 11 3.1 9 9 0 1 0 20.9 13Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',search:'<circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 6 6"/>'};return `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type]}</svg>`;};
function header(active='home'){return `<header class="header"><div class="header-inner"><a class="brand" href="/" aria-label="LeLiz 首页"><img src="/images/karina-avatar.jpg" width="40" height="40" alt="柳志敏主题头像"><span>${escape(site.name)}</span></a><nav id="navigation" aria-label="主导航"><a ${active==='home'?'aria-current="page"':''} href="/">首页</a><a href="/#projects">开源</a><a href="/#experience">经历</a><a href="/#publications">论文</a><a ${active==='blog'?'aria-current="page"':''} href="/blog/">博客</a></nav><div class="header-actions"><button class="icon-button theme-toggle" aria-label="切换浅色主题"><span class="sun">${icon('sun')}</span><span class="moon">${icon('moon')}</span></button><button class="icon-button menu-toggle" aria-label="展开导航" aria-expanded="false" aria-controls="navigation">${icon('menu')}</button></div></div></header>`;}
function footer(){return `<footer class="footer container"><span>© ${new Date().getFullYear()} ${escape(site.name)}</span><div><a href="${safeUrl(site.github)}" target="_blank" rel="noopener noreferrer">GitHub</a><a href="/feed.xml">RSS</a><a href="/write/">写文章</a></div></footer>`;}
function page({title,description=site.description,pathname='/',body,active='home',extra=''}){return `<!doctype html><html lang="zh-CN" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title===site.name?title:title+' · '+site.name)}</title><meta name="description" content="${escape(description)}"><meta name="color-scheme" content="dark light"><link rel="canonical" href="${escape(site.url+pathname)}"><link rel="icon" href="/favicon.svg"><link rel="alternate" type="application/rss+xml" title="LeLiz 博客" href="/feed.xml"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/katex/katex.min.css"><script>try{document.documentElement.dataset.theme=localStorage.getItem('leliz-pages-theme')||'dark'}catch{}</script><script src="/assets/site.js" defer></script>${extra}</head><body><a class="skip-link" href="#main">跳到正文</a>${header(active)}${body}${footer()}</body></html>`;}
function articleRow(post){return `<a class="article-row" href="/blog/${post.slug}/" data-category="${escape(post.category)}" data-search="${escape(post.title+' '+post.excerpt+' '+post.body)}"><time datetime="${post.date}">${post.date.replaceAll('-','.')}</time><div><div class="article-meta"><span>${escape(post.category)}</span>${post.example?'<span>示例</span>':''}</div><h3>${escape(post.title)}</h3><p>${escape(post.excerpt)}</p></div></a>`;}
function projectCard(project){return `<a class="project" href="${safeUrl(project.url)}" target="_blank" rel="noopener noreferrer"><div class="project-symbol">${icon('code')}</div><div class="project-body"><h3>${escape(project.name)}</h3><p>${escape(project.description)}</p><div class="project-meta"><span>${escape(project.language)}</span><span>${escape(project.repository)}</span></div></div><span class="project-link">GitHub</span></a>`;}
const experience=site.experience.length?site.experience.map(item=>`<div class="experience-item"><span>${escape(item.period)}</span><h3>${escape(item.title)}</h3><p>${escape(item.description)}</p></div>`).join(''):'<p class="empty">教育与实习经历待补充。</p>';
const papers=site.publications.length?site.publications.map(p=>`<article class="paper"><h3>${p.url?`<a href="${safeUrl(p.url)}" target="_blank" rel="noopener noreferrer">${escape(p.title)}</a>`:escape(p.title)}</h3><p>${escape(p.authors)}</p><span>${escape(p.venue)} · ${escape(p.year)}</span></article>`).join(''):'<p class="empty">暂无已发表论文。</p>';
if(path.dirname(out)!==root||path.basename(out)!=='dist')throw new Error('Unsafe build output directory');
fs.rmSync(out,{recursive:true,force:true});
fs.mkdirSync(out,{recursive:true});
fs.cpSync('public',out,{recursive:true});
fs.mkdirSync(path.join(out,'assets'),{recursive:true});
fs.copyFileSync('src/site.css',path.join(out,'assets/site.css'));
fs.copyFileSync('src/site.js',path.join(out,'assets/site.js'));
fs.cpSync('node_modules/katex/dist',path.join(out,'assets/katex'),{recursive:true,filter:source=>!source.endsWith('.mjs')&&!source.endsWith('README.md')});
fs.copyFileSync('node_modules/katex/LICENSE',path.join(out,'assets/katex/LICENSE'));
fs.mkdirSync(path.join(out,'assets/editor'),{recursive:true});
fs.copyFileSync('node_modules/markdown-it/dist/browser/markdown-it.umd.min.js',path.join(out,'assets/editor/markdown-it.min.js'));
fs.copyFileSync('node_modules/markdown-it/LICENSE',path.join(out,'assets/editor/markdown-it.LICENSE'));
fs.copyFileSync('node_modules/markdown-it-texmath/texmath.js',path.join(out,'assets/editor/texmath.js'));
fs.copyFileSync('node_modules/markdown-it-texmath/license.txt',path.join(out,'assets/editor/texmath.LICENSE'));
fs.copyFileSync('src/editor.js',path.join(out,'assets/editor/editor.js'));
write('index.html',page({title:site.name,body:`<main id="main" class="container"><section class="hero"><div><h1>${escape(site.name)}<span>.</span></h1><p class="hero-summary">${escape(site.description)}</p><div class="hero-links"><a class="button primary" href="#projects">开源项目</a><a class="button" href="/blog/">阅读博客</a></div><a class="profile-link" href="${safeUrl(site.github)}" target="_blank" rel="noopener noreferrer">github.com/Holly229567</a></div><figure class="hero-photo"><img src="/images/karina-hero.jpg" alt="柳志敏主题照片" width="1620" height="1080" fetchpriority="high"></figure></section><section id="projects" class="section"><div class="section-heading"><h2>开源项目</h2><a href="${safeUrl(site.github+'?tab=repositories')}" target="_blank" rel="noopener noreferrer">全部项目</a></div>${site.projects.map(projectCard).join('')}</section><div class="profile-sections"><section id="experience" class="section"><h2>经历</h2>${experience}</section><section id="publications" class="section"><h2>论文</h2>${papers}</section></div><section class="section last-section"><div class="section-heading"><h2>博客</h2><a href="/blog/">全部文章</a></div><div class="article-list">${posts.slice(0,3).map(articleRow).join('')||'<p class="empty">暂无文章。</p>'}</div></section></main>`}));
write('blog/index.html',page({title:'博客',pathname:'/blog/',active:'blog',body:`<main id="main" class="container blog-page"><div class="page-heading"><h1>博客</h1><a href="/write/" class="button">写文章</a></div><div class="blog-controls"><div class="filter-tabs" aria-label="文章分类">${['全部','研究','开发','随笔'].map((c,i)=>`<button data-category-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><label class="search">${icon('search')}<input id="article-search" type="search" placeholder="搜索文章" aria-label="搜索文章"></label></div><div class="article-list">${posts.map(articleRow).join('')}</div><p class="empty" id="no-results" hidden>没有匹配的文章。</p></main>`}));
for(const post of posts)write(`blog/${post.slug}/index.html`,page({title:post.title,description:post.excerpt,pathname:`/blog/${post.slug}/`,active:'blog',body:`<main id="main" class="article-page"><a class="back-link" href="/blog/">返回博客</a><header class="article-heading"><h1>${escape(post.title)}</h1><div class="article-byline"><span>${escape(site.name)}</span><time datetime="${post.date}">${post.date}</time><span>${escape(post.category)}</span>${post.example?'<span>示例文章</span>':''}</div></header><article class="prose">${post.html}</article><div class="article-footer"><a href="/blog/">全部文章</a><a href="https://github.com/${escape(site.repository)}/edit/main/content/posts/${post.slug}.md" target="_blank" rel="noopener noreferrer">在 GitHub 编辑</a></div></main>`}));
write('write/index.html',page({title:'写文章',pathname:'/write/',active:'blog',extra:'<meta name="robots" content="noindex"><script src="/assets/editor/markdown-it.min.js" defer></script><script src="/assets/katex/katex.min.js" defer></script><script src="/assets/editor/texmath.js" defer></script><script src="/assets/editor/editor.js" defer></script>',body:`<main id="main" class="container write-page"><div class="page-heading"><h1>写文章</h1><a href="https://github.com/${escape(site.repository)}/tree/main/content/posts" target="_blank" rel="noopener noreferrer">管理文章</a></div><form id="editor-form" data-repository="${escape(site.repository)}"><label>标题<input id="post-title" placeholder="文章标题" maxlength="160" required></label><div class="form-row"><label>文章地址<input id="post-slug" placeholder="my-first-post" pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="100" required></label><label>分类<select id="post-category"><option>随笔</option><option>研究</option><option>开发</option></select></label><label>日期<input id="post-date" type="date" required></label></div><label>摘要<input id="post-excerpt" placeholder="一两句话介绍文章" maxlength="500"></label><div class="editor-toolbar"><div class="filter-tabs"><button type="button" id="edit-tab" aria-pressed="true">写作</button><button type="button" id="preview-tab" aria-pressed="false">预览</button></div><button type="button" class="text-button" id="new-draft">清空并新建</button></div><textarea id="post-content" aria-label="文章正文" placeholder="支持 Markdown、代码与数学公式。" required></textarea><article id="post-preview" class="prose editor-preview" hidden></article><p id="editor-message" role="status" hidden></p><div class="editor-actions"><button type="button" class="button" id="save-draft">保存到此浏览器</button><button type="button" class="button" id="download-post">下载 Markdown</button><button type="submit" class="button primary">在 GitHub 发布</button></div><p class="editor-help">发布将在 GitHub 完成。提交文章后，网站会自动更新。</p></form></main>`}));
write('404.html',page({title:'页面不存在',body:'<main id="main" class="container missing-page"><h1>页面不存在</h1><p>检查文章地址，或返回首页。</p><a class="button primary" href="/">回到首页</a></main>'}));
write('feed.xml',`<?xml version="1.0" encoding="utf-8"?><rss version="2.0"><channel><title>LeLiz 博客</title><link>${escape(site.url)}</link><description>${escape(site.description)}</description><language>zh-cn</language>${posts.map(p=>`<item><title>${escape(p.title)}</title><link>${site.url}/blog/${p.slug}/</link><guid>${site.url}/blog/${p.slug}/</guid><description>${escape(p.excerpt)}</description><pubDate>${new Date(p.date+'T00:00:00+08:00').toUTCString()}</pubDate></item>`).join('')}</channel></rss>`);
write('sitemap.xml',`<?xml version="1.0" encoding="utf-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/blog/',...posts.map(p=>`/blog/${p.slug}/`)].map(p=>`<url><loc>${site.url}${p}</loc></url>`).join('')}</urlset>`);
write('robots.txt',`User-agent: *\nAllow: /\nDisallow: /write/\nSitemap: ${site.url}/sitemap.xml\n`);
write('.nojekyll','');
console.log(`Built ${posts.length} published article(s) and ${site.projects.length} project(s).`);
